import type { Config } from "tailwindcss";

const config: Config = {
    darkMode: "class",
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "primary-container": "#0056d2",
                "inverse-on-surface": "#edf1f5",
                "secondary": "#515f74",
                "on-secondary-container": "#57657a",
                "on-primary-fixed": "#001847",
                "secondary-container": "#d5e3fc",
                "secondary-fixed": "#d5e3fc",
                "surface-dim": "#d6dade",
                "surface-bright": "#f6fafe",
                "surface-container-high": "#e4e9ed",
                "on-surface-variant": "#424654",
                "on-primary-container": "#ccd8ff",
                "on-error": "#ffffff",
                "primary": "#0040a1",
                "outline-variant": "#c3c6d6",
                "on-secondary-fixed-variant": "#3a485b",
                "on-error-container": "#93000a",
                "surface-container-lowest": "#ffffff",
                "inverse-surface": "#2c3134",
                "surface-container-highest": "#dfe3e7",
                "error": "#ba1a1a",
                "surface": "#f6fafe",
                "tertiary-container": "#006e2e",
                "on-tertiary-fixed": "#002109",
                "tertiary-fixed": "#7ffc97",
                "surface-variant": "#dfe3e7",
                "on-primary": "#ffffff",
                "secondary-fixed-dim": "#b9c7df",
                "tertiary-fixed-dim": "#62df7d",
                "primary-fixed-dim": "#b2c5ff",
                "surface-tint": "#0056d2",
                "on-background": "#171c1f",
                "on-tertiary": "#ffffff",
                "surface-container": "#eaeef2",
                "surface-container-low": "#f0f4f8",
                "on-surface": "#171c1f",
                "background": "#f6fafe",
                "on-secondary-fixed": "#0d1c2e",
                "primary-fixed": "#dae2ff",
                "inverse-primary": "#b2c5ff",
                "outline": "#737785",
                "on-secondary": "#ffffff",
                "tertiary": "#005321",
                "on-tertiary-fixed-variant": "#005320",
                "on-tertiary-container": "#75f28e",
                "on-primary-fixed-variant": "#0040a1",
                "error-container": "#ffdad6"
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
};
export default config;
